# Generated by Django 5.2.4 on 2025-08-06 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profilevisit_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilevisit',
            name='visit_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='profilevisit',
            index=models.Index(fields=['visitor', 'visited'], name='accounts_pr_visitor_4e3aee_idx'),
        ),
    ]
